In [6]:
""" Phase 1 : Step 1: 
Standard method to import Pandas library into the code to use 
for data analysis and manipulation 
Pandas library is loaded into current script's memory. 
Once imported we can gain access to all of its powerful data structures
pd is the alias name for pandas library. 
"""
import pandas as pd

In [7]:
""" Step 2: 
read_csv is pandas built in function designed specifically to read CSV (Comma Seperated Values) files.
It takes teh file and automatically converts it into a Data Frame.
Salary_Data.csv is the name of the input file. Since no path is specified, 
Python expectst this to be located in the same folder as Python Script of Jupyter Notes 
Dataset= This is the assignment step where the entire contents of the fiel is stored in a 
variable called Dataset
"""
dataset=pd.read_csv("Salary_Data.csv")

In [4]:
dataset

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [12]:
""" Step 3:
To retrieve the input column into a variable we give 
input variable = dataframe[["input column name""]
"""
independent=dataset[["YearsExperience"]]
independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [24]:
""" Step 4: 
To retrieve the output column into a variable we give 
output variable = dataframe[["output column name""]
"""
dependent=dataset[["Salary"]]
dependent

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [16]:
#So with step 3 & step4 , we have split both input and output separately
#Now we have to separate training set and test set

In [25]:
""" Step 5 : 
sklearn (scikit-learn) is the most popular machine learning library in Python
Model_Selection is s specific module inside which it has tools for evaluating and tuning machine learning  models
We fetch only train_test_split instead of importing entire Model_Selection
train_test_split shuffles and chops single dataset into two pieces : train set(70% - 80%) and test set(30% - 20%)

The output of train_test_split function returns 4 parameters - x_train, x_test, y_train and y_test
x_train and X_test - refers to input and y_train and y_test refers to output

"""
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [26]:
""" Step 6 : 
The below two lines are procedures 
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
fit method (function) substitutes the values in the formula.
weight and bias would have been calculated once the fit function is executed.
Model is ready once the weight and bias are found out
"""
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [27]:
""" Step 7 : 
Store the weight 
"""
weight=regressor.coef_
weight

array([[9360.26128619]])

In [28]:
""" Step 8 : 
Store the bias  
"""
bias=regressor.intercept_
bias

array([26777.3913412])

In [29]:
""" Step 9 : 
Evaluate the model  cross check the result 
"""
y_pred = regressor.predict(x_test)

In [31]:
""" Step 10 :
r square - (Coefficient of Determination) is the standard metric used to evaluate how 
well a regression model performed
r_score nearly to one emans performing  very well
if it is near to zero, it is not performing well
"""
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.9740993407213511

In [40]:
""" Step 11: 
we have to save the model once it is confirmed that model is perfroming well

import pickle : 
Python's standard pickle module is loaded .
Pickling means serialization - 
converting a complex Python object (like a machine learning model, with all its internal 
weights and math formul) into a raw stream of bytes that can be saved to a disk file

filename="finalized_model_linear.sav"
.sav or .pkl are the standard file extensions used for saving machine learning models 
pickle.dump(regressor,open(filename,'wb'))

pickle.dump(regressor,open(filename,'wb'))
The above command actually writes the model to hard drive. It has two steps : 

a. open(filename,'wb') 
This opens the file for writing in binary mode - wb .Since machine language model is not 
regular text, it must be written as binary code.

b. pickle.dump(regressor,....)
This takes teh trained regressor model object,  converts into bytes, and dumps into 
that open binary file

we can find a new file with .sav extesnion in the project folder.
This is used for deployment. It also allows you to make instant predictions
on new data  without needing the original dataset or spending time retraining the model
"""
import pickle 
filename="finalized_model_linear.sav"
pickle.dump(regressor,open(filename,'wb'))

In [44]:
""" Step 12 : 
Load machine learning model in Python 
open("finalized_model_linear.sav",'rb')
This opens the file containing your model. 'rb' stands for read binary, which is 
required as the model was saved as binary
pickle.load() 
This reads the binary stream and converts it back into a fully functioning Pandas/scikit-learn object
Loaded_model= This stores the restored model into a new variable name.
Loaded_model now possess the exact same patterns, weights and formulas it learned during its original 
training session.
result=loaded_model.predict([[15]])
the above line is used to predict the salary for 15 years of experience
"""
loaded_model=pickle.load(open("finalized_model_linear.sav",'rb'))
result=loaded_model.predict([[15]])

C:\Users\keert\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [45]:
""" step 13 : 
Display the predicted salary for 15 years
"""
result

array([[167181.3106341]])